/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ReturnRequest } from "./ReturnRequest";
import { ReturnRequestCountArgs } from "./ReturnRequestCountArgs";
import { ReturnRequestFindManyArgs } from "./ReturnRequestFindManyArgs";
import { ReturnRequestFindUniqueArgs } from "./ReturnRequestFindUniqueArgs";
import { DeleteReturnRequestArgs } from "./DeleteReturnRequestArgs";
import { ReturnRequestService } from "../returnRequest.service";
@graphql.Resolver(() => ReturnRequest)
export class ReturnRequestResolverBase {
  constructor(protected readonly service: ReturnRequestService) {}

  async _returnRequestsMeta(
    @graphql.Args() args: ReturnRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ReturnRequest])
  async returnRequests(
    @graphql.Args() args: ReturnRequestFindManyArgs
  ): Promise<ReturnRequest[]> {
    return this.service.returnRequests(args);
  }

  @graphql.Query(() => ReturnRequest, { nullable: true })
  async returnRequest(
    @graphql.Args() args: ReturnRequestFindUniqueArgs
  ): Promise<ReturnRequest | null> {
    const result = await this.service.returnRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ReturnRequest)
  async deleteReturnRequest(
    @graphql.Args() args: DeleteReturnRequestArgs
  ): Promise<ReturnRequest | null> {
    try {
      return await this.service.deleteReturnRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
